# Generated by Django 4.0.6 on 2022-07-31 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='like_users',
            field=models.ManyToManyField(blank=True, related_name='like_posts', to=settings.AUTH_USER_MODEL, verbose_name='좋아요한 사람'),
        ),
        migrations.AddField(
            model_name='post',
            name='view_counts',
            field=models.PositiveIntegerField(default=0, verbose_name='조회수'),
        ),
        migrations.AlterField(
            model_name='post',
            name='hashtags',
            field=models.ManyToManyField(blank=True, related_name='post_hashtag', to='post.hashtag'),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_status', to='post.status', verbose_name='상태'),
        ),
    ]
